language: php

php:
  - 7.2
  - 7.3

env:
  - LARAVEL='^5.8' TESTBENCH='^3.8' COMPOSER_FLAGS='--prefer-stable'
  - LARAVEL='^6.0' TESTBENCH='^4.0' COMPOSER_FLAGS='--prefer-stable'
  - LARAVEL='6.x-dev' TESTBENCH='^4.0'

matrix:
  fast_finish: true
  allow_failures:
    - env: LARAVEL='6.x-dev' TESTBENCH='^4.0'

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update
  - travis_retry composer require --no-update --no-interaction "illuminate/support:${LARAVEL}" "orchestra/testbench:${TESTBENCH}"

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist --no-suggest

script: ./vendor/bin/phpunit --verbose --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
